shamefullyHoist: true
packages: []
catalogs:
  build:
    '@intlify/unplugin-vue-i18n': ^11.0.3
    '@shikijs/markdown-it': ^3.21.0
    '@unocss/eslint-config': ^66.6.0
    '@vitejs/plugin-vue': ^6.0.3
    beasties: ^0.4.1
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.57.0
    shiki: ^3.21.0
    unocss: ^66.6.0
    unplugin: ^3.0.0
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^31.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^29.2.0
    unplugin-vue-router: ^0.19.2
    vite: 7.3.1
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.3.3
    vite-plugin-pwa: ^1.2.0
    vite-plugin-vue-devtools: ^8.0.5
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^28.2.2
    vite-ssg-sitemap: ^0.10.0
  dev:
    '@daotl/eslint-config': ^4.6.3
    '@daotl/tsconfig': ^0.1.2
    '@iconify-json/carbon': ^1.2.18
    '@nx/eslint': 22.4.2
    '@nx/vite': 22.4.2
    '@nx/web': 22.4.2
    '@prettier/plugin-xml': ^3.4.2
    '@vitest/coverage-v8': 4.0.18
    '@vitest/ui': 4.0.18
    '@vue-macros/volar': ^3.1.2
    '@vue/test-utils': ^2.4.6
    cross-env: ^10.1.0
    cypress: ^15.9.0
    cypress-vite: ^1.8.0
    dotenv-cli: ^11.0.0
    eslint: ^9.39.2
    eslint-plugin-cypress: ^5.2.1
    eslint-plugin-format: ^1.3.1
    https-localhost: ^4.7.1
    lefthook: ^2.0.16
    nx: 22.4.2
    postcss: ^8.5.6
    postcss-html: ^1.8.1
    postcss-styled-syntax: ^0.7.1
    postcss-syntax: ^0.36.2
    remeda: ^2.33.4
    sass: ^1.97.3
    stylelint: ^17.0.0
    stylelint-config-html: ^1.1.0
    stylelint-config-property-sort-order-smacss: ^11.0.0
    stylelint-config-recommended-scss: ^17.0.0
    stylelint-config-recommended-vue: ^1.6.1
    stylelint-webpack-plugin: ^5.0.1
    taze: ^19.9.2
    typescript: ^5.9.3
    vitest: 4.0.18
    vue-tsc: ^3.2.4
  frontend:
    '@unhead/vue': ^2.1.2
    '@unocss/reset': ^66.6.0
    '@vueuse/core': ^14.1.0
    nprogress: ^0.2.0
    pinia: ^3.0.4
    vue: ^3.5.27
    vue-i18n: ^11.2.8
    vue-router: ^4.6.4
  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3
onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
