shamefullyHoist: true

packages: []

catalogs:
  build:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@shikijs/markdown-it': ^3.9.2
    '@unocss/eslint-config': ^66.4.2
    '@vitejs/plugin-vue': ^6.0.1
    beasties: ^0.3.5
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.46.2
    shiki: ^3.9.2
    unocss: ^66.4.2
    unplugin: ^2.3.5
    unplugin-auto-import: ^20.0.0
    unplugin-element-plus: ^0.9.1
    unplugin-vue-components: ^29.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^29.1.0
    unplugin-vue-router: ^0.15.0
    vite: ^7.1.2
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.3.2
    vite-plugin-pwa: ^1.0.2
    vite-plugin-vue-devtools: ^8.0.0
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^28.0.0
    vite-ssg-sitemap: ^0.10.0

  dev:
    '@daotl/eslint-config': ^4.6.3
    '@daotl/tsconfig': ^0.1.2
    '@iconify-json/carbon': ^1.2.13
    '@nx/eslint': 21.1.3
    '@nx/vite': 21.1.3
    '@nx/web': 21.1.3
    '@prettier/plugin-xml': ^3.4.2
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vue-macros/volar': ^3.0.0-beta.21
    '@vue/test-utils': ^2.4.6
    cross-env: ^10.0.0
    cypress: ^14.5.4
    cypress-vite: ^1.6.0
    dotenv-cli: ^10.0.0
    eslint: ^9.33.0
    eslint-plugin-cypress: ^5.1.1
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    lefthook: ^1.12.3
    nx: 21.1.3
    postcss: ^8.5.6
    postcss-html: ^1.8.0
    postcss-styled-syntax: ^0.7.1
    postcss-syntax: ^0.36.2
    remeda: ^2.30.0
    sass: ^1.90.0
    stylelint: ^16.23.1
    stylelint-config-html: ^1.1.0
    stylelint-config-property-sort-order-smacss: ^10.0.0
    stylelint-config-recommended-scss: ^16.0.0
    stylelint-config-recommended-vue: ^1.6.1
    stylelint-webpack-plugin: ^5.0.1
    taze: ^19.0.2
    typescript: ^5.9.2
    vitest: ^3.2.4
    vue-tsc: ^3.0.5

  frontend:
    '@unhead/vue': ^2.0.14
    '@unocss/reset': ^66.4.2
    '@vueuse/core': ^13.6.0
    beasties: ^0.3.5
    element-plus: ^2.9.6
    nprogress: ^0.2.0
    pinia: ^3.0.3
    vue: ^3.5.18
    vue-i18n: ^11.1.11
    vue-router: ^4.5.1

  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
