packages: []

catalogs:

  build:
    '@intlify/unplugin-vue-i18n': ^6.0.5
    '@shikijs/markdown-it': ^3.2.1
    '@unocss/eslint-config': ^66.1.0-beta.7
    '@vitejs/plugin-vue': ^5.2.3
    beasties: ^0.2.0
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.37.0
    shiki: ^3.2.1
    unocss: ^66.1.0-beta.7
    unplugin: ^2.2.2
    unplugin-auto-import: ^19.1.2
    unplugin-vue-components: ^28.4.1
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^28.3.1
    unplugin-vue-router: ^0.12.0
    vite: ^6.2.3
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.0.0
    vite-plugin-pwa: ^0.21.2
    vite-plugin-vue-devtools: ^7.7.2
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^26.0.0
    vite-ssg-sitemap: ^0.8.1

  dev:
    '@daotl/eslint-config': ^4.6.1
    '@daotl/tsconfig': ^0.1.2
    '@iconify-json/carbon': ^1.2.8
    '@intlify/unplugin-vue-i18n': ^6.0.3
    '@nx/eslint': 20.5.0
    '@nx/vite': 20.5.0
    '@nx/web': 20.5.0
    '@prettier/plugin-xml': ^3.4.1
    '@vitest/coverage-v8': ^3.0.8
    '@vitest/ui': ^3.0.8
    '@vue-macros/volar': ^3.0.0-beta.7
    '@vue/test-utils': ^2.4.6
    cross-env: ^7.0.3
    cypress: ^14.2.1
    cypress-vite: ^1.6.0
    dotenv-cli: ^8.0.0
    eslint: ^9.23.0
    eslint-plugin-cypress: ^4.2.0
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    lefthook: ^1.11.3
    nx: 20.5.0
    postcss: ^8.5.3
    postcss-html: ^1.8.0
    postcss-styled-syntax: ^0.7.1
    postcss-syntax: ^0.36.2
    remeda: ^2.21.0
    sass: ^1.85.1
    stylelint: ^16.15.0
    stylelint-config-html: ^1.1.0
    stylelint-config-property-sort-order-smacss: ^10.0.0
    stylelint-config-recommended-scss: ^14.1.0
    stylelint-config-recommended-vue: ^1.6.0
    stylelint-webpack-plugin: ^5.0.1
    taze: ^19.0.2
    typescript: ^5.8.2
    vitest: ^3.0.9
    vue-tsc: ^2.2.8

  frontend:
    '@unhead/vue': ^2.0.2
    '@unocss/reset': ^66.1.0-beta.7
    '@vueuse/core': ^13.0.0
    '@vueuse/head': ^2.0.0
    beasties: ^0.2.0
    element-plus: ^2.9.5
    nprogress: ^0.2.0
    pinia: ^3.0.1
    vue: ^3.5.13
    vue-i18n: ^11.1.2
    vue-router: ^4.5.0

  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
